[package]
name = "tgh-tg"
version = "0.1.0"
edition.workspace = true

[dependencies]
tgh-core = { path = "../core" }
grammers-client.workspace = true
grammers-session = { version = "0.10", default-features = false, features = ["serde"] }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
tgh-native = { path = "../native" }
base64 = "0.22"
serde.workspace = true
